# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tractor Hacking
email: afite@calpoly.edu
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to hacking into John Deere tractors and publishing
  our findings in an open source manner.  The project is through California
  Polytechnic State University's Capstone I/II class and sponsored by iFixit.
  Material on this site is protected from DMCA takedown by a DMCA exemption
  granted by the US Copyright Office.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tractorhacking.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: TractorHacking

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed

header_pages:
   - about.md
   - polycan.md
   - greenboard.md
   - documentation.md
   - data.md
   - contributors.md
   - usage.md

collections:
   polycan:
      output: true
      title: PolyCAN
   greenboard:
      output: true
      title: GreenBoard
   documentation:
      output: true
      title: Documentation
   idinfo:
      output: true
      title: ID Information
